### ISSUE TITLE
VCV crash - when right click on an empty slot 

### ISSUE THREAD

**Issue by keymanpal** [Paul-Dempsey/pachde-hc-one#10]
Macosx M1 Pro Ventura (13.5.2) - ContinuuMini
 - when right click on an empty slot, VCV crash.
Always - either prior to gathering the presets or after...
Happens on USER as well FAVOURITE or SYSTEM.

**Comment by Paul-Dempsey** [comment]
Thank you -- one missing null check. I fixed this just after the release ;-).

**Comment by Paul-Dempsey** [comment]
Fixed in Beta 4 release
