### ISSUE TITLE
"Default" Heartbeat causes audio glitch

### ISSUE THREAD

**Issue by keymanpal** [Paul-Dempsey/pachde-hc-one#11]
Macosx M1 Pro Ventura (13.5.2) - ContinuuMini

 Heartbeat causes audio glitch, brief interruption  on long held notes.

Using OPTIONS-Module - Surpress Heartbeat handshake - does cure; no more audio glitch.

**Comment by Paul-Dempsey** [comment]
This is documented in the manual, and why there is an option. It's not something I can fix in my software -- that's on the hardware side.

**Comment by Paul-Dempsey** [comment]
I've decided to remove the periodic heartbeat altogether- the audio glitches are intolerable for a music device.

**Comment by Paul-Dempsey** [comment]
Fixed in Beta 4 release. No more recurring handshake! You can still ping the device manually in the menu if you want to check the DSP levels.
